### PR TITLE
temp fix for broken vagrant box link

### PR DESCRIPTION
**Pull request by dmitry-sher**
added a solution as described here:
https://github.com/hashicorp/vagrant/issues/9442

### CODE REVIEW

**Comment by dmitry-sher** [comment]
kudos to @kasgel and @kentonv , the PR is now much more mature

**Comment by Rivierg** [comment]
Hi, I’m trying to install sandstorm using vagrant-spk for the first time and your fix really helped me, thanks a lot !
One thing before merging though, it is breaking the compatibility with the LEMP stack. In [https://github.com/sandstorm-io/vagrant-spk/blob/master/stacks/lemp/setup.sh](https://github.com/sandstorm-io/vagrant-spk/blob/master/stacks/lemp/setup.sh), php5 is to be installed. With the Debian version you specify in this file, it should be php7.0 ... I am trying to check it now see if I can fix it, then I will upload it here.

**Comment by dmitry-sher** [comment]
@Rivierg do you want me to include #211 in #209 ?
@kentonv can somebody at some point really merge PRs?

**Comment by ocdtrekkie** [comment]
Kenton will probably check in again on the weekend.

I think the best case is likely to keep 209 and 211 separate so people get credit for their contribution, and they arguably fix different issues, one being the actual operation of vagrant-spk and one fixing a stack.

**Comment by Rivierg** [comment]
I agree that it should probably stay separated. As @ocdtrekkie said in #211 , handling the different OS and php versions could be done by the user (but it’s not great for a first tutorial, so we rather need to refine the documents for php).

**Comment by kentonv** [comment]
Thanks!

**Pull request merged**
